In [1]:
!pip install numpy  pandas matplotlib seaborn plotly


In [2]:
import numpy  as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


In [3]:
print(np.__version__)

2.4.4


In [4]:
arr=np.array([10,20,30])
print(arr)

[10 20 30]


In [5]:
#creaing   ARRAY USING ARRAY()
#NP.ARRAY(OBJECT)------ syntax
import numpy as np
arr=np.array([1,2,3,4])#--------------#1-D ARRAY
print(arr)


[1 2 3 4]


In [6]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])#---------------------2d array
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
import numpy as np 
arr=np.array([[[1,2,3],[4,5,6],[2,3,4]]])# ------------3 d array

print(arr)

[[[1 2 3]
  [4 5 6]
  [2 3 4]]]


In [8]:
#creating ary with zeroes
#np.zero((row,columns)) #--------syntax
import numpy as np
# arr=np.zeros((2,3))#creating ary with zeroes
# print(arr)
# np.ones((2,3))#creating ary with ones
# np.eye(3)#creating ary with identiy matrix
np.arange(1,10)#creating ary with arange()

np.arange(1,10,2)#creating ary with arange() (1st,last,gapdene k liye )
np.linspace(1,10,5)#creating ary with linspace






array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:

# creating random array
np.random.rand(3)#-------� 1. Random float values
np.random.randint(1,10,5)#-------� 1. Random integer values
np.random.choice([1,2,3,4])#? 3. Random choice


In [ ]:
import numpy as np 
np.full((2,2), 7)#-------Creating Array with Full Value


array([[7, 7],
       [7, 7]])

# tOPIC 3: Array Properties (shape, ndim, dtype, size) ?

In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [ ]:
arr = np.array([1,2,3,4])
print(arr.shape)

(4,)


In [ ]:
arr = np.array([[1,2],[3,4]])
print(arr.ndim)#---------ndim--Array kitne dimension ka hai

2


In [1]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.size)##Total elements count

arr = np.array([1,2,3])
print(arr.dtype)
arr = np.array([1.5, 2.5])
print(arr.dtype)

NameError: name 'np' is not defined

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)

Shape: (2, 3)
Dimensions: 2
Size: 6


# TOPIC 4: Indexing & Slicing (VERY IMPORTANT + tricky)

In [2]:
import numpy as np
arr = np.array([10, 20, 30, 40])
print(arr[0])
print(arr[1]) # 20
print(arr[2]) # 30



10
20
30


In [3]:
#� 3. Negative Indexing �
# � Last se access karna
print(arr[-1]) # 40
print(arr[-2]) # 30

40
30


In [ ]:
# ? 4. Slicing (Range Access)
# ? Multiple elements ek saath
# ? Syntax:
# arr[start:end]
# ? Example:
print(arr[1:3])

In [1]:
import numpy as np
arr = np.array([10, 20, 30, 40])
print(arr[:3]) # start se 3 tak
print(arr[2:]) # 2 se end tak
print(arr[::2])# 5. Step Slicing 



[10 20 30]
[30 40]
[10 30]


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr[0,1])
# #✔ row 0
# ✔ column 1

print(arr[1,2]) # 6
# 2d slicing 

print(arr[:, 1])
# Row slicing:
print(arr[0, :])
# 8. Fancy Indexing ?
# Specific indexes select karna

arr = np.array([10,20,30,40])
print(arr[[0,2,3]])


In [4]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
arr = np.array([10,20,30,40])
print(arr[arr > 20])
arr[::-1] # reverse array

[30 40]


array([40, 30, 20, 10])