In [1]:
!pip install numpy  pandas matplotlib seaborn plotly


In [2]:
import numpy  as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


In [3]:
print(np.__version__)

2.4.4


In [4]:
arr=np.array([10,20,30])
print(arr)

[10 20 30]


In [5]:
#creaing   ARRAY USING ARRAY()
#NP.ARRAY(OBJECT)------ syntax
import numpy as np
arr=np.array([1,2,3,4])#--------------#1-D ARRAY
print(arr)


[1 2 3 4]


In [6]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])#---------------------2d array
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
import numpy as np 
arr=np.array([[[1,2,3],[4,5,6],[2,3,4]]])# ------------3 d array

print(arr)

[[[1 2 3]
  [4 5 6]
  [2 3 4]]]


In [8]:
#creating ary with zeroes
#np.zero((row,columns)) #--------syntax
import numpy as np
# arr=np.zeros((2,3))#creating ary with zeroes
# print(arr)
# np.ones((2,3))#creating ary with ones
# np.eye(3)#creating ary with identiy matrix
np.arange(1,10)#creating ary with arange()

np.arange(1,10,2)#creating ary with arange() (1st,last,gapdene k liye )
np.linspace(1,10,5)#creating ary with linspace






array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [9]:

# creating random array
np.random.rand(3)#1. Random float values
np.random.randint(1,10,5)# 1. Random integer values
np.random.choice([1,2,3,4])#3. Random choice


np.int64(1)

In [10]:
import numpy as np 
np.full((2,2), 7)#-------Creating Array with Full Value


array([[7, 7],
       [7, 7]])

# tOPIC 3: Array Properties (shape, ndim, dtype, size) ?

In [11]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [12]:
arr = np.array([1,2,3,4])
print(arr.shape)

(4,)


In [13]:
arr = np.array([[1,2],[3,4]])
print(arr.ndim)#---------ndim--Array kitne dimension ka hai

2


In [14]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.size)##Total elements count

arr = np.array([1,2,3])
print(arr.dtype)
arr = np.array([1.5, 2.5])
print(arr.dtype)

6
int64
float64


In [15]:
arr = np.array([[1,2,3],[4,5,6]])
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)

Shape: (2, 3)
Dimensions: 2
Size: 6


# TOPIC 4: Indexing & Slicing (VERY IMPORTANT + tricky)

In [16]:
import numpy as np
arr = np.array([10, 20, 30, 40])
print(arr[0])
print(arr[1]) # 20
print(arr[2]) # 30



10
20
30


In [17]:
#� 3. Negative Indexing �
# � Last se access karna
print(arr[-1]) # 40
print(arr[-2]) # 30

40
30


In [18]:
#4. Slicing (Range Access)

print(arr[1:3])

[20 30]


In [19]:
import numpy as np
arr = np.array([10, 20, 30, 40])
print(arr[:3]) # start se 3 tak
print(arr[2:]) # 2 se end tak
print(arr[::2])# 5. Step Slicing 



[10 20 30]
[30 40]
[10 30]


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr[0,1])
# #✔ row 0
# ✔ column 1

print(arr[1,2]) # 6
# 2d slicing 

print(arr[:, 1])
# Row slicing:
print(arr[0, :])
# 8. Fancy Indexing 
# Specific indexes select karna

arr = np.array([10,20,30,40])
print(arr[[0,2,3]])


In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
arr = np.array([10,20,30,40])
print(arr[arr > 20])
arr[::-1] # reverse array

[30 40]


array([40, 30, 20, 10])

# TOPIC 5: Mathematical Operations in NumPy

## Isme tum seekhogi:
+, -, *, /
power
sqrt
vector operations ?

In [13]:
import numpy as np 
a=np.array([1,2,3])
b = np.array([4,5,6])#+
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)
print(a + 2)
np.sum(a)
np.mean(a)
np.min(a)
np.max(a)
np.std(a)
np.sqrt(a)
np.exp(a)
np.log(a)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
[3 4 5]


array([0.        , 0.69314718, 1.09861229])

In [15]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a + b)

np.dot(a, b)

[5 7 9]


np.int64(32)

In [16]:
arr = np.array([[1,2],[3,4]])
print(arr + 2)

[[3 4]
 [5 6]]


In [19]:
arr = np.array([[1,2,3],[4,5,6]])
np.sum(arr, axis=0)
np.sum(arr, axis=1)

array([ 6, 15])

In [21]:
a = np.array([1,2,3])
b = 2
print(a + b)

[3 4 5]


TOPIC 6: Reshaping Arrays + Flatten + Ravel

In [ ]:
# arr.reshape(rows, columns)

import numpy as np
arr = np.array([1,2,3,4,5,6])
new_arr = arr.reshape(3,2)
print(new_arr)
arr.reshape(2, -1)
arr = np.array([1,2,3,4])
print(arr.reshape(2,2))


[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]


In [34]:
arr = np.array([[1,2],[3,4]])
print(arr.flatten())
print(arr.ravel())
arr = np.array([[1,2],[3,4]])
a = arr.flatten()
b = arr.ravel()

[1 2 3 4]
[1 2 3 4]


In [35]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,2,2))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# TOPIC 7: Iteration in NumPy (Looping Techniques FULL DETAIL ?

In [37]:
# import numpy as np
# arr = np.array([10,20,30,40])
# for x in arr:
# print(x)

import numpy as np

arr = np.array([10,20,30,40])

for x in arr:
    print(x)

10
20
30
40


In [39]:
arr = np.array([[1,2,3],[4,5,6]])
for row in arr:
 print(row)

[1 2 3]
[4 5 6]


In [41]:
arr = np.array([10,20,30])   
for index, value in np.ndenumerate(arr):
 print(index, value)

(0,) 10
(1,) 20
(2,) 30


In [43]:
arr = np.array([[1,2],[3,4]])
for index, value in np.ndenumerate(arr):
 print(index, value)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [45]:
arr = np.array([[1,2],[3,4]])
for x in np.nditer(arr):
 print(x)

1
2
3
4


In [49]:
arr = np.array([1,2,3])
for x in np.nditer(arr, op_flags=['readwrite']):
 x[...] = x * 2
 print(arr)

[2 2 3]
[2 4 3]
[2 4 6]


In [52]:
arr = np.array([1,2,3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['float']):
 print(x)

1.0
2.0
3.0


# TOPIC 8: Copy vs View (FULL DETAIL ?)

TOPIC 8: Copy vs View (FULL DETAIL ?)

In [53]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print("a:", a)
print("b:", b)

a: [1 2 3]
b: [100   2   3]


In [54]:
a = np.array([1,2,3])
b = a.view()
b[0] = 100
print("a:", a)
print("b:", b)

a: [100   2   3]
b: [100   2   3]


In [55]:
a = np.array([1,2,3])
b = a.copy()
c = a.view()
print(b.base)
print(c.base)

None
[1 2 3]


? TOPIC 9: Stacking & Splitting Arrays
Isme tum seekhogi:,,
vstack(),
hstack(),
split(),
array_split() ?



In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
result = np.vstack((a,b))
print(result)
result = np.hstack((a,b))
print(result)
np.column_stack((a,b))
np.row_stack((a,b))



[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


/tmp/ipykernel_3634/3575439688.py:9: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
arr = np.array([1,2,3,4,5,6])
result = np.split(arr, 3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [62]:
arr = np.array([1,2,3,4,5])
np.array_split(arr, 3)

[array([1, 2]), array([3, 4]), array([5])]

In [63]:
arr = np.array([[1,2],[3,4],[5,6]])
np.array_split(arr, 3)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

In [64]:
np.array_split(arr, 2, axis=1)

[array([[1],
        [3],
        [5]]),
 array([[2],
        [4],
        [6]])]

? TOPIC 10: NumPy Random Module

? Isme tum seekhogi:,

random numbers,
rand vs randint,
seed concept ?

In [68]:
import numpy as np
np.random.rand(3)
np.random.rand(2,3)
np.random.randint(1, 10, 5)
np.random.choice([10,20,30,40])

np.int64(40)

In [69]:
arr = np.array([1,2,3,4])
np.random.shuffle(arr)
print(arr)

[2 4 3 1]


In [70]:
np.random.seed(42)
print(np.random.rand(3))

[0.37454012 0.95071431 0.73199394]


In [71]:
np.random.normal(0, 1, 5)

array([-1.11188012,  0.31890218,  0.27904129,  1.01051528, -0.58087813])

In [72]:
np.random.uniform(1, 10, 5)

array([2.65064059, 3.73818019, 5.72280788, 4.88750517, 3.62106226])

In [73]:
np.random.uniform(1, 10, 5)

array([6.50667605, 2.25544475, 3.62930184, 4.29725659, 5.10462986])

TOPIC 11: Broadcasting (DEEP + MOST IMPORTANT ???)


In [74]:
import numpy as np
a = np.array([1,2,3])
b = 2
print(a + b)

[3 4 5]


In [75]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([10,20,30])
print(a + b)

[[11 22 33]
 [14 25 36]]


In [76]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[10], [20]])
print(a + b)

[[11 12 13]
 [24 25 26]]


In [78]:
# a = np.array([1,2,3])
# b = np.array([1,2])
# print(a + b)

? TOPIC 12: Advanced Indexing (Fancy + Boolean Deep)

In [ ]:
np.random.rand(3)
np.random.randint(1, 10, 5)
np.random.choice([1,2,3,4])
np.full((2,2), 7)

np.int64(3)

? TOPIC 3: Array Properties (shape, ndim, dtype, size) ?

In [82]:


import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [83]:
arr = np.array([1,2,3,4])
print(arr.shape)

(4,)


In [84]:
arr = np.array([[1,2],[3,4]])
print(arr.ndim)

2


? TOPIC 13: Linear Algebra + Matrix Operations (

In [ ]:
import numpy as np
A = np.array([[1,2], [3,4]])
B = np.array([[5,6],[7,8]])
print(A + B)

[[ 6  8]
 [10 12]]


In [87]:
B = np.array([[5,6],[7,8]])
print(A + B)

[[ 6  8]
 [10 12]]


In [88]:
np.matmul(A, B)

array([[19, 22],
       [43, 50]])

In [89]:
A @ B

array([[19, 22],
       [43, 50]])

In [91]:
np.dot(A, B)
print(A.T)

[[1 3]
 [2 4]]


In [92]:
np.linalg.det(A)

np.float64(-2.0000000000000004)

In [93]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [94]:
A = np.array([[2,1],[1,1]])
B = np.array([5,3])
x = np.linalg.solve(A, B)
print(x)

[2. 1.]
